### ISSUE TITLE
Trophy Slots does not load

### ISSUE THREAD

**Issue by Mumberthrax** [Lomeli12/TrophySlots#11]
log: http://paste.ee/p/fZ6Vk

Running minecraft 1.8, forge 11.14.4.1563, lomlib 4.1.0, trophy slots 2.0.0

Minecraft starts up, forge lists lomlib as being loaded in the mod options menu, but does not list trophy slots. loading up a world works as normal, no indication that trophy slots has activated, no inventory slots seem to be blocked.

**Comment by Lomeli12** [comment]
Trophy Slots doesn't need LomLib, but it does require Forgelin http://minecraft.curseforge.com/projects/forgelin

**Comment by Mumberthrax** [comment]
ah, that would explain it. Sorry. I didn't see any indications on the readme or the curseforge page about forgelin. I probably overlooked it. :x
