### ISSUE TITLE
Crash on opening inventory

### ISSUE THREAD

**Issue by Mumberthrax** [Lomeli12/TrophySlots#12]
http://paste.ee/p/cYcGu

Trophy Slots 2.0.0, Forgelin 1.8-0.1.0-0.12.200-d7.jar, Forge 11.14.4.1563, Minecraft 1.8, Java 8, MultiMC 0.4.7, Windows 7

Game loads, new world generates - i see lots of red messages pop up in multimc's console - things seem ok in-game until I hit e to open the inventory. Then I get a crash.

**Comment by Lomeli12** [comment]
This is gonna take a while to fix because I already updated my dev environment to 1.8.8, but I'd like to push a fix to this to 1.8 before I update the mod to 1.8.8 thus requiring a temp 1.8 dev environment for the fix.

**Comment by Lomeli12** [comment]
Fix for 1.8 should be available soon on CurseForge once it's approved. Will be pushing 1.8.8 fix to the repo soonish. http://minecraft.curseforge.com/projects/trophy-slots/files/2270389

**Comment by Mumberthrax** [comment]
nice! Sorry for bugging you about these things.
