### ISSUE TITLE
[1.8.8][3.0.0version] A small experience problem

### ISSUE THREAD

**Issue by gxy17886** [Lomeli12/TrophySlots#14]
hi,I find a small problem .When I use crafting table unlock achievements ,new unlock slot can‘t be place  things .BUT exit the crafting table it can place things,This is a bad experience.  
what time it hanppen.for example.IT happen to  unlock "time to farm " and "time to mine" and "time to strike "(these are achievement name)and so on .

**Comment by Lomeli12** [comment]
This is a known issue in Trophy Slots that has existed since it's initial release and which I haven't found a nice way to fix it.

**Comment by Lomeli12** [comment]
Reopening this the attempted fix I did for this actually broke the player's inventory and so I reverted to a previous commit.

**Comment by Lomeli12** [comment]
Never found a proper fix for this. And now MC Advancements only registered complete once a player is no longer in a GUI, so this issue is no longer an issue..
