### ISSUE TITLE
1.16.5 Forge version?

### ISSUE THREAD

**Issue by vizthex123** [Lomeli12/TrophySlots#27]
Is that planned? Or is there something similar to this for 1.16.5 Forge?

**Comment by vizthex123** [comment]
Edit: I did find [this mod](https://www.curseforge.com/minecraft/mc-mods/inventory-free), but I really liked this one.

**Comment by NixityNull** [comment]
I really hope this updates

**Comment by NixityNull** [comment]
IT WORKS! Despite being 1.16.1, it actually WORKS on 1.16.5! I am so glad I tried it just in case!

**Comment by Lomeli12** [comment]
Existing 1.16 version should work on all revisions of 1.16
