### ISSUE TITLE
Slot display is misaligned when effects are active

### ISSUE THREAD

**Issue by Kobata** [Lomeli12/TrophySlots#7]
![2015-04-13_13 51 39](https://cloud.githubusercontent.com/assets/2323933/7121876/9252f554-e1e5-11e4-9ccc-61c02bf80732.png)

In the normal inventory display, when a potion effect is being displayed, [this code](https://github.com/Lomeli12/TrophySlots/blob/master/src/main/java/net/lomeli/trophyslots/client/EventHandlerClient.java#L44-L45) is incorrect, because guiLeft and guiTop on the actual gui have been modified to not be 'centered' according to the size of the gui.

The obvious way to fix this would be simply to get the variables directly off the GuiContainer.

**Comment by Lomeli12** [comment]
Fixed with fa3f2fe2b8095477662eb98ddc5793516bae0bdd because I love to make things more complicated for myself.
